# TODO: Support x86 Python builds.
# TODO: Support Python 3.5, 3.6, 3.7, 3.8 using VC 14.2

name: release

on:
  push:
    branches:
      - master

jobs:

  build27:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python 2.7 x64
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
        architecture: x64

    - name: Download VC 9.0
      run: curl -O https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi

    - name: Install VC 9.0
      run: msiexec VCForPython27.msi

    - name: Install dependencies
      run: |
        pip install --upgrade setuptools
        pip install --upgrade cython
        pip install --upgrade wheel

    - name: Build Binary Wheel
      run: python setup.py bdist_wheel

    - name: Archive Dist Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist-windows-latest-27-x64
        path: dist
