] disabled for testing

name: winbdist

on:
  push:
    branches:
      - master

jobs:

  build-38-x64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Download Build Tools for Visual Studio 2019
      run: Invoke-WebRequest -Uri https://aka.ms/vs/16/release/vs_buildtools.exe -OutFile vs_buildtools.exe

    - name: Run vs_buildtools.exe install
      run: >
        ./vs_buildtools.exe --quiet --wait --norestart --nocache --includeRecommended
          --add Microsoft.VisualStudio.Workload.VCTools
          --add Microsoft.VisualStudio.Component.VC.140

    - name: Set up Python 3.8 x64
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: x64

    - name: Install dependencies
      run: |
        pip install --upgrade cython
        pip install --upgrade wheel
      shell: bash {0}

    - name: Build Binary Wheel
      run: python setup.py bdist_wheel

    - name: Archive Dist Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist-windows-latest-38-x64
        path: dist
