# TODO: Support x86 Python builds.

name: winbdist

on:
  push:
    branches:
      - master

jobs:

  build-27-x64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python 2.7 x64
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
        architecture: x64

    - name: Download VC 9.0
      run: curl -O http://www.grantjenks.com/VCForPython27.msi

    - name: Install VC 9.0
      run: msiexec /i VCForPython27.msi ALLUSERS=1

    - name: Install dependencies
      run: |
        pip install --upgrade setuptools
        pip install --upgrade cython
        pip install --upgrade wheel
      shell: bash {0}

    - name: Build Binary Wheel
      run: python setup.py bdist_wheel

    - name: Archive Dist Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist-windows-latest-27-x64
        path: dist

  build-38-x64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python 3.8 x64
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: x64

    - name: Download VS Build Tools
      run: curl -O http://www.grantjenks.com/vs_buildtools.exe

    - name: Install VS Build Tools
      run: vs_buildtools.exe

    - name: Install dependencies
      run: |
        pip install --upgrade setuptools
        pip install --upgrade cython
        pip install --upgrade wheel
      shell: bash {0}

    - name: Build Binary Wheel
      run: python setup.py bdist_wheel

    - name: Archive Dist Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist-windows-latest-38-x64
        path: dist
